FROM omop-tools

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libpq-dev

RUN install2.r --error --ncpus 2 \
    RPostgres

RUN mkdir -p /output /jdbc \
    && R -e 'DatabaseConnector::downloadJdbcDrivers("postgresql", pathToDriver = "/jdbc")'
